# Configuration Netlify pour KhanelConcept React App avec vidéo Cloudinary
[build]
  base = "frontend"
  publish = "frontend/build"
  command = "yarn install && yarn build"

# Variables d'environnement pour le build
[build.environment]
  NODE_VERSION = "18"
  CI = "false"
  GENERATE_SOURCEMAP = "false"
  DISABLE_ESLINT_PLUGIN = "true"
  REACT_APP_BACKEND_URL = "https://your-backend-url.com/api"

# Plugin Cloudinary pour optimiser les médias
[[plugins]]
  package = "netlify-plugin-cloudinary"
  [plugins.inputs]
    cloudName = "ddulasmtz"
    deliveryType = "upload"
    # Répertoires d'images à optimiser
    imagePaths = [
      "images/**/*"
    ]
    # Répertoires vidéos à optimiser  
    videoPaths = [
      "public/**/*.mp4",
      "src/**/*.mp4"
    ]

# Headers de sécurité avec support Cloudinary
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "same-origin"
    # CSP mise à jour pour autoriser Cloudinary
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com https://cdn.jsdelivr.net; img-src 'self' data: https: blob:; media-src 'self' https://res.cloudinary.com https:; connect-src 'self' https: wss:; worker-src 'self' blob:;"

# Headers spécifiques pour les vidéos
[[headers]]
  for = "*.mp4"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    
# Headers pour les assets statiques
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirections pour React Router (SPA)
[[redirects]]
  from = "/villa/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Règles pour l'admin
[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200
