# Docker Compose pour KhanelConcept API
# Inclut API, MongoDB, et monitoring

version: '3.8'

services:
  # API Backend
  khanelconcept-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/khanelconcept
      - ENVIRONMENT=production
    env_file:
      - .env.production
    depends_on:
      - mongodb
    volumes:
      - ./logs:/var/log/khanelconcept
    restart: unless-stopped
    networks:
      - khanelconcept-network

  # Base de données MongoDB
  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
      - MONGO_INITDB_DATABASE=khanelconcept
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: unless-stopped
    networks:
      - khanelconcept-network

  # Interface d'administration MongoDB (optionnel)
  mongo-express:
    image: mongo-express:1.0.0
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password123
      - ME_CONFIG_MONGODB_URL=mongodb://admin:password123@mongodb:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - khanelconcept-network

  # Nginx Reverse Proxy (optionnel)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - khanelconcept-api
    restart: unless-stopped
    networks:
      - khanelconcept-network

volumes:
  mongodb_data:
    driver: local

networks:
  khanelconcept-network:
    driver: bridge